# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Compile executable
        run : |
             wget https://go.dev/dl/go1.19.linux-amd64.tar.gz
             rm -rf /usr/local/go && tar -C /usr/local -xzf go1.19.linux-amd64.tar.gz
             export PATH=$PATH:/usr/local/go/bin
             cd handler 
             go get github.com/aws/aws-lambda-go/lambda
             GOOS=linux go build main.go
             mkdir function
             zip function/function.zip main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::491330015265:role/github-actions-role
          role-session-name: image-store-session
          aws-region: ap-south-1

      - name: Upload package to S3
        run: ${{format('aws s3 sync --delete ./function s3://image-store-packages/{0}', $GITHUB_SHA)}}

  deploy:
    runs-on : ubuntu-latest
    needs: build

    steps:
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ImageStoreStack
          template: ${{format('{0}/imageStoreStack.yaml', $GITHUB_WORKSPACE)}}
